name: Install dependencies

on: 
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare
      uses: Pcrab/pblive-lib/.github/workflows/prepare.yml@main
    - name: Check code style
      run: pnpm lint