name: Install dependencies

on: 
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare
      uses: Pcrab/pblive-lib/.github/workflows/prepare.yml@main
    - name: Check tests
      run: pnpm test